### ISSUE TITLE
Upgrade to jest v24-26 and babel to version 7

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/docs-searchbar.js#182]
Because or Jest version is v23 we have vulnerabilities caused by `yargs-parser`. 
We tried to fix it by using the resolutions, this introduced more problems. Also, resolutions are patches and not a solution.

linked issue: https://github.com/facebook/jest/issues/7424

This vulnerability has been fixed in jest `v24>`

Jest version 24 uses Babel 7:
https://jestjs.io/blog/2019/01/25/jest-24-refreshing-polished-typescript-friendly#typescript-support

But we use a previous version that is not compatible with jest v24.

To fix this problem properly we should consider upgrading jest to v24 or higher and babel to version 7.

**Comment by curquiza** [comment]
Also related to #123 I think.
