### ISSUE TITLE
Scroll issue on Firefox 74.0

### ISSUE THREAD

**Issue by curquiza** [meilisearch/docs-searchbar.js#25]
Someone reported an issue on Firefox 74.0 (Ubuntu):

![Selection_001](https://user-images.githubusercontent.com/20380692/78764261-96c08780-7986-11ea-8624-e8fefb69e46f.png)

The scroll is activated and we do not see the MeiliSearch logo anymore.

**Comment by bidoubiwa** [comment]
Can someone still exists or if it is fixed?

**Comment by bidoubiwa** [comment]
We welcome user to use the [meilisearch-docsearch](https://github.com/tauri-apps/meilisearch-docsearch) of tauri that is a better version of this project. For this reason, we deprecate this repository in favor of theirs.
