### ISSUE TITLE
Add browser tests with Cypress

### ISSUE THREAD

**Issue by curquiza** [meilisearch/docs-searchbar.js#339]
Cypress is a library to run tests in a browser.

To ensure this package work, we would like to add tests with Cypress.

Follow this guide to implement it: https://github.com/meilisearch/integration-guides/blob/main/guides/cypress.md

Feel free to ask any question about this issue implementation 🙂

**Comment by TheLaw1337** [comment]
on it

**Comment by bidoubiwa** [comment]
Hey @TheLaw1337 Thanks a lot for giving an interest in this PR. I'm assigning you. [Here is a guide](https://github.com/meilisearch/integration-guides/blob/main/guides/cypress.md) on how to use cypress in our repos. 

We can only guarantee the assignment for 5 days. After which if someone else wants to give it a try we will change the assignation. Good luck with the PR!

**Comment by TheLaw1337** [comment]
#434 please do review

**Comment by devcer** [comment]
Is this issue still open? Can I write some more tests for this?
