### ISSUE TITLE
Remove use of `!important` in CSS

### ISSUE THREAD

**Issue by mdubus** [meilisearch/docs-searchbar.js#352]
There are  `!important` in CSS. This is a bad practice and it would be nice to remove them.
If so, we have to be careful that it might be breaking.

![Capture d’écran 2021-06-07 à 16 22 40](https://user-images.githubusercontent.com/30866152/121033568-9a2ee900-c7ac-11eb-9182-b3c622a346d7.png)

**Comment by Sugyanee** [comment]
Hey, can I work on this issue?

**Comment by bidoubiwa** [comment]
Sure! Good luck :)

**Comment by Sugyanee** [comment]
I'll try my best

**Comment by arpit282** [comment]
Hola, can I also work on this?

**Comment by bidoubiwa** [comment]
To not block contributors on issues that are not completed, we change the assignees after 5 days without a PR. Since it has been 5days I'm removing your assignment.

I'm assigning you @arpit282
