### ISSUE TITLE
Make docs-searchbar compatible with typescript

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/docs-searchbar.js#479]
For the moment when using docs-searchbar.js in an typescript environment, it raises an error because of a lack of declaration file. This can be prevented by providing a type file.

Better explanation on the issue [here](https://github.com/meilisearch/docs-searchbar.js/issues/479#issuecomment-1268240992).

**Comment by AyushK-101** [comment]
I would like to work on this issue

**Comment by bidoubiwa** [comment]
Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the real volunteers contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/README.md). 

We are looking forward to reviewing your PR 😊

**Comment by AyushK-101** [comment]
@bidoubiwa I would like to know more about the issue, as in how can I reproduce it. From what I am getting, we can set allowJs to true in compilerOptions in tsconfig.json to run the Javascript files in typescript environment

**Comment by bidoubiwa** [comment]
In some environments they need to have access to a type file. Something like `index.d.ts`.  You can find more information on how to do this [here](https://medium.com/jspoint/typescript-type-declaration-files-4b29077c43). 

An example of a repository that does this is axios which [code-base is in JS](https://github.com/axios/axios/blob/v1.x/index.d.ts) but they provide a type file.
