### ISSUE TITLE
Cypress tests should not work with a remote MeiliSearch instance

### ISSUE THREAD

**Issue by curquiza** [meilisearch/docs-searchbar.js#519]
Maybe I'm wrong and the Cypress tests are not working with a remote MeiliSearch instance, but it looks like they are using the `https://docs-search-bar.meiliseasrch.com` instance, which is not recommended. This remote instance is indeed the MeiliSearch instance used by the documentation to provide a search bar. It's not an easy task to upgrade this instance since it's very impactful for the users of the docs. Our CI should definitely not rely on this instance.

Plus, it's not convenient at all to update a remote instance to make CI tests work. A CI should be as independent as possible.
We should download locally (in the CI) a MeiliSearch that will be used for the cypress tests 🙂

**Comment by curquiza** [comment]
Can we close this @bidoubiwa ?

**Comment by bidoubiwa** [comment]
Yes! My bad
