### ISSUE TITLE
Question: search bar's cardinality with indexes

### ISSUE THREAD

**Issue by yankeeinlondon** [meilisearch/docs-searchbar.js#525]
Can the searchbar work with multiple indexes or only one?

**Comment by curquiza** [comment]
Hello @ksnyde 

This search bar works only with MeiliSearch, and MeiliSearch is not currently able to provide a multi indexes search at the moment. But it's planned for 2022, we plan to start the work during Q2

**Comment by bidoubiwa** [comment]
This is related to [meilisearch-engine](https://github.com/meilisearch/meilisearch/)! To track multi index search please refer to the releases of meilisearch :)
