### ISSUE TITLE
Update of the URL linking to the SVG of the `Meilisearch` part appearing in `Powered by ..`

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/docs-searchbar.js#534]
Following rebranding the `Powered By MeiliSearch` requires a new link to the SVG of the image. While it is not hosted on a CDN we cannot change the link. 

<img width="575" alt="Screenshot 2022-01-27 at 14 50 04" src="https://user-images.githubusercontent.com/33010418/151372502-71cd1c33-8bda-4cd8-84a3-4fa83c810663.png">

Waiting on @qdequele to provide a link

**Comment by qdequele** [comment]
The link is normally the same as previously. https://res.cloudinary.com/meilisearch/image/upload/v1643306912/Logo/logo_text.svg

**Comment by curquiza** [comment]
Looks like it's fixed by @bidoubiwa right? :)

**Comment by bidoubiwa** [comment]
It is !
