### ISSUE TITLE
Fix playground

### ISSUE THREAD

**Issue by curquiza** [meilisearch/docs-searchbar.js#552]
The playground uses ` https://docs-search-bar.meilisearch.com` that is down today. We need to update the playground to make it usable again.

https://github.com/meilisearch/docs-searchbar.js/blob/a419a4a2f3cf7af10bb47b76e07dc246125b289f/playgrounds/javascript/src/index.js#L6

**Comment by curquiza** [comment]
@bidoubiwa I let you explain what is the best solution to solve this 🙂

**Comment by bidoubiwa** [comment]
Hey! The playground is using the remote server. We need to change that with a local server containing documents compatible with the playground. 
To achieve this, these must be done: 

- [ ] Create a setup script ([like this one](https://github.com/meilisearch/instant-meilisearch/blob/main/tests/env/react/setup.js))
- [ ] Add in the contributing guide how to use the script
- [ ] Add the command to launch the script in package.json

**Comment by bidoubiwa** [comment]
fixed by #563
