### ISSUE TITLE
MeiliSearchCommunicationError

### ISSUE THREAD

**Issue by linlai163** [meilisearch/docs-searchbar.js#582]
Hey guys, I meet a problem when I use meilisearch-js.

In the old version, It works great. But yesterday, I did some refactor(nothing to do with meilisearch-js) and then, after I deployed my website, I found I can't use the search service.I've send request with masterKey. But problem is still here.

```javascript
docs-searchbar.min.js:2 Uncaught (in promise) MeiliSearchCommunicationError: request to https://trantor-meilisearch.app.terminus.io/indexes/trantor/search failed, reason: connect ECONNREFUSED
    at t.<anonymous> (docs-searchbar.min.js:2:67933)
    at docs-searchbar.min.js:2:64772
    at Object.next (docs-searchbar.min.js:2:64877)
    at docs-searchbar.min.js:2:63815
    at new Promise (<anonymous>)
    at r (docs-searchbar.min.js:2:63563)
    at t.request (docs-searchbar.min.js:2:67624)
    at t.<anonymous> (docs-searchbar.min.js:2:68597)
    at docs-searchbar.min.js:2:64772
    at Object.next (docs-searchbar.min.js:2:64877)
```
and this is the code in my project
```javascript
componentDidMount() {
  window.docsSearchBar({
    hostUrl: 'https://trantor-meilisearch.app.terminus.io/',
    apiKey: '',
    indexUid: 'trantor',
    inputSelector: '#search-input',
    meilisearchOptions: { limit: 99, matches: true }
  }, { limit: 50000 })
}
```
You can reproduce the problem in https://trantor-doc-test-mobile.app.terminus.io/v1.0.x/doc/quick-start/base-trantor

**Comment by bidoubiwa** [comment]
Hey @linlai163 
Could you give me the following information:
- your version of `docs-searchbar.js`
- your version of meilisearch

**Comment by linlai163** [comment]
@bidoubiwa 

- I didn't specify the version of `docs-searchbar.js`, it was loaded by CDN.It should be the newest version. https://cdn.jsdelivr.net/npm/docs-searchbar.js@latest/dist/cdn/docs-searchbar.min.js

- the version of `meilisearch` is v0.23.1

> by the way, thanks

**Comment by bidoubiwa** [comment]
Hey @linlai163 
Could you update meilisearch to the latest (v0.27) **or** specify the version of docs-searchbar to be: v2.0.1 or less ?
Versions above 2.0.1 are only compatible with meilisearch v0.25 and more. 

The easiest for you is just to specify the version of docs-searchbar but I would suggest you stay up to date with the latest versions of Meilisearch. We do not guarantee support for the older versions until we are in version 1.

**Comment by linlai163** [comment]
@bidoubiwa It did solve the problem, thanks
