### ISSUE TITLE
React based SDK

### ISSUE THREAD

**Issue by OlegGulevskyy** [meilisearch/docs-searchbar.js#597]
Are there any plans to make this based on a react with possibly some API exposed for tweaking it, so anyone can customize it as and how they want, using components based UI etc etc?

**Comment by bidoubiwa** [comment]
There is for the moment no plans to make this react compatible. From my understanding of react, would it not require to create an other package ?

**Comment by OlegGulevskyy** [comment]
Ideally, yes
But thanks for answering
