### ISSUE TITLE
Allow the docs-searchbar to be invoked using keyboard shortcut

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/docs-searchbar.js#603]
**Description**
The idea is to allow users to invoke the Meilisearch frontend search bar using a keyboard shortcut like ```cmd + K```. A keyboard shortcut implementation to invoke the search bar is already present in the Algolia search bar and also Slack search bar and it makes it easier for users to do a search rather than have to go to the search bar in the navigation bar every time. 

**Basic example**
The user can invoke the search by using a keyboard shortcut. 
Algolia's implementation for reference: 
![image](https://user-images.githubusercontent.com/19529592/171015031-453bb9d4-1465-460c-a4f4-4546641363f1.png)
![image](https://user-images.githubusercontent.com/19529592/171015059-73bf02ad-b31b-4608-bbd1-36fe5d1f5773.png)

**Comment by shivaylamba** [comment]
Would love to know your feedback @bidoubiwa

**Comment by bidoubiwa** [comment]
Hello! 
Unfortunately this is not planned. `docs-searchbar.js` tooked inspiration from the previous version of the docs-scrapper of Algolia. They completely reworked their package and it has now way more features that this package does not have. 

When we update this package we might have that feature!
