### ISSUE TITLE
Add a configuration to display searchbar in a modal

### ISSUE THREAD

**Issue by coleshirley** [meilisearch/docs-searchbar.js#623]
**Description**
It would be really nice to be able to display the search bar in a modal similar to the way Algolia does it. Then we could add multiple buttons on the site to trigger the search modal via events

**Basic example**
<img width="2045" alt="Screen Shot 2022-07-07 at 11 01 53 AM" src="https://user-images.githubusercontent.com/84236864/177830213-3ecbf002-68ca-45e3-8434-74e343b13b15.png">

**Comment by bidoubiwa** [comment]
Hey @coleshirley 
Is this the new autocomplete tool of algolia? Could you link me their repo?

**Comment by theowenyoung** [comment]
@bidoubiwa https://github.com/algolia/docsearch , I also like the new design of doc search. I wonder if it's easy to fork it and adapt to meilisearch.

**Comment by bidoubiwa** [comment]
Hey @theowenyoung I will look into their new package and see how we can adapt it (if we can). 

Thanks a lot for the suggestion!

**Comment by theowenyoung** [comment]
You're welcome! thanks for the great lib! I notice it on <https://tailwindcss.com/>, it's really smooth!

**Comment by arranf** [comment]
This would be awesome! 

I've looked at doing this myself and it's more work than I'd like!

**Comment by bidoubiwa** [comment]
@arranf yes unfortunately it's a lot of work

**Comment by bidoubiwa** [comment]
Closing this in preference of a compatibility with [autocomplete](https://github.com/algolia/autocomplete)

**Comment by coleshirley** [comment]
> Closing this in preference of a compatibility with [autocomplete](https://github.com/algolia/autocomplete)

To clarify is this compatibility something that is being made by meilisearch or something left up to us end developers?

**Comment by bidoubiwa** [comment]
Giving it a try is in our short term roadmap :) We hope that the compatibility will be possible without having to re-invent the wheel! I'll keep you updated when we start the work
