### ISSUE TITLE
Fix README table of contents links

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/docs-searchbar.js#654]
In the table of content, the links are broken. To fix it, matching emojis should be added to every title referenced by the table of content.

**Comment by vaibhavmishra4g** [comment]
Could you assign it to me?

**Comment by Samarthasbhat** [comment]
I will fix this issue

**Comment by bidoubiwa** [comment]
Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the real volunteers contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/README.md). 

We are looking forward to reviewing your PR 😊

**Comment by Samarthasbhat** [comment]
What are the content should i need to change like table of content after clicking the link it should redirect ??

**Comment by deepesh16b** [comment]
Please assign this to me

**Comment by bidoubiwa** [comment]
Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the real volunteers contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/README.md). 

We are looking forward to reviewing your PR 😊

**Comment by AyushK-101** [comment]
@bidoubiwa I have made a PR regarding this issue, please review it
