### ISSUE TITLE
Add a Scroll To Top Button

### ISSUE THREAD

**Issue by stringer1000** [meilisearch/docs-searchbar.js#660]
**Description**
Add a scroll to top button for users to easily move to the top.
If approved, please assign me this issue.

**Comment by bidoubiwa** [comment]
Hey @stringer1000, How do you envision this?

**Comment by bidoubiwa** [comment]
We welcome user to use the [meilisearch-docsearch](https://github.com/tauri-apps/meilisearch-docsearch) of tauri that is a better version of this project. For this reason, we deprecate this repository in favor of theirs.
