### ISSUE TITLE
Auto search when search input has content and actived

### ISSUE THREAD

**Issue by imvkmark** [meilisearch/docs-searchbar.js#668]
When there is content in the search box, click the search box, the search box is activated, and the search result window is not automatically opened

Expected: When the search box has content and is activated
1. All texts are in the selected state, which is convenient to directly enter new content for searching
2. Open the search result page to display the search content, which is convenient to adjust the search conditions again

![image](https://user-images.githubusercontent.com/150127/198004073-24b2e9b6-1a46-4d9d-8c5e-6b795bcf3c92.png)
site: https://wulicode.com

**Comment by bidoubiwa** [comment]
Hey @imvkmark it seems that there is a bug with your docs-searchbar. Can you provide the code initializing it?

**Comment by imvkmark** [comment]
@bidoubiwa , Thank for your help. 
There has 2 parts in my blog.

at main.js, the `hostUrl` can opened in browser
```
docsSearchBar({
    hostUrl: 'https://platform.jkfxpt.com:7770',
    apiKey: 'f1f95fdb28d7eda1cea1b47d1ae162802954fca8762c1f05dfd19cb403ba1d9b',
    indexUid: 'wulicode-scraper',
    inputSelector: '#search-bar-input',
    debug: false, // Set debug to true if you want to inspect the dropdown
})
```

at html
```
<div className="columns meilisearch">
    <div class="column column-left is-4-tablet is-4-desktop is-4-widescreen  order-1">
        <div class=" card widget">
            <input type="search" id="search-bar-input" placeholder="search use meilisearch"/>
        </div>
    </div>
</div>
```

**Comment by bidoubiwa** [comment]
what happens if you add docsSearchBar in a script tag inside your HTML file ?

```html
<script>
docsSearchBar({
    hostUrl: 'https://platform.jkfxpt.com:7770',
    apiKey: 'f1f95fdb28d7eda1cea1b47d1ae162802954fca8762c1f05dfd19cb403ba1d9b',
    indexUid: 'wulicode-scraper',
    inputSelector: '#search-bar-input',
    debug: false, // Set debug to true if you want to inspect the dropdown
})
</script>
```

**Comment by imvkmark** [comment]
I'm use hexo for static site, so i can't add script to jsx file.

**Comment by imvkmark** [comment]
Because of the slow access of cdn in China, I download the js file to my source directory. so you may cannot find access log from network panel.

**Comment by bidoubiwa** [comment]
if you console.log `docsSearchBar` does it appear in your browser logs?

**Comment by imvkmark** [comment]
> if you console.log `docsSearchBar` does it appear in your browser logs?

![image](https://user-images.githubusercontent.com/150127/199646372-d0e18a47-4673-42ee-8d6b-62bd12c7dbeb.png)

Yes

**Comment by bidoubiwa** [comment]
@imvkmark okey I just understood the issue. You are right, because of the Chinese CDN it was not working at all on my end (or it could work but I should have waited longer).

So the improvement you are requiring: If there is text in the input and focus is put on the input, the results component should automatically open ?

**Comment by imvkmark** [comment]
Yes, That's what i mean. like notion's search bar.

**Comment by bidoubiwa** [comment]
We welcome user to use the [meilisearch-docsearch](https://github.com/tauri-apps/meilisearch-docsearch) of tauri that is a better version of this project. For this reason, we deprecate this repository in favor of theirs.
