### ISSUE TITLE
Does it support Multi-index search?

### ISSUE THREAD

**Issue by yueling-li** [meilisearch/docs-searchbar.js#720]
**Description**
Brief explanation of the feature.

**Basic example**
If the proposal involves something new or a change, include a basic example. How would you use the feature? In which context?

**Other**
Any other things you want to add.

**Comment by bidoubiwa** [comment]
Hey @yueling-li, currently it does not support the multi-index search but it can be added. How would you see this being implemented ?

we change `indexUid` param to be able to accept an array?

```
   docsSearchBar({
        hostUrl: 'https://mymeilisearch.com',
        apiKey: 'XXX',
        indexUid: ['index_1', 'index_2'], // indexUid can be an array, or a string. 
        inputSelector: '#search-bar-input',
      })
```

**Comment by bidoubiwa** [comment]
We welcome user to use the [meilisearch-docsearch](https://github.com/tauri-apps/meilisearch-docsearch) of tauri that is a better version of this project. For this reason, we deprecate this repository in favor of theirs.
