### ISSUE TITLE
New Docsearch

### ISSUE THREAD

**Issue by Mat4m0** [meilisearch/docs-searchbar.js#752]
**Description**
Will the new docs-searchbar what is currently implemented in the new meilisearch docs be available in the future to use for e.g. Docusaurus?

![image](https://github.com/meilisearch/docs-searchbar.js/assets/79974907/81df6ba6-cdcd-4c92-b3a9-c8fd1b48e237)

Many thanks and keep up the awesome work!
Ma4m0

**Comment by bidoubiwa** [comment]
Hey @Mat4m0 !

This is a home made search bar. It's not currently planned but we will try to provide one asap.

Meanwhile this one is more advanced: https://github.com/tauri-apps/meilisearch-docsearch

**Comment by Mat4m0** [comment]
Thanks! Exactly what I was looking for 😊

**Comment by bidoubiwa** [comment]
I'm closing the issue if it's resolved for you :)
